security:
    encoders:
        King\Bundle\BackendBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: $2a$12$w/aHvnC/XNeDVrrl65b3dept8QcKqpADxUlbraVXXsC03Jam5hvoO
                        roles: 'ROLE_USER'
                    admin:
                        password: $2a$12$HmOsqRDJK0HuMDQ5Fb2.AOLMQHyNHGD0seyjU3lEVusjT72QQEIpW
                        roles: 'ROLE_ADMIN'
        kingbackendbundle:
            entity:
                class: KingBackendBundle:User
                property: username
    firewalls:
        secured_area:
            pattern:   ^/admin
            anonymous: ~
            form_login:
                login_path: king_backend_login
                check_path: king_backend_login_check
                provider: kingbackendbundle
            logout:
                path:   king_backend_logout
                target: king_backend_login
            remember_me:
                key:      "%secret%"
                lifetime: 604800
                path:     /
                domain:   ~

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin/account, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }