security:
    encoders:
        King\Bundle\BackendBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        kingbackendbundle:
            entity:
                class: KingBackendBundle:User
                property: username
                
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_MASTER: [ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_GOD: [ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_MASTER, ROLE_ALLOWED_TO_SWITCH]
    
    firewalls:
        secured_area:
            provider: kingbackendbundle
            pattern: ^/admin
            anonymous: ~
            form_login:
                check_path: king_backend_login_check
            logout:
                path:   king_backend_logout
                target: king_backend_login
            remember_me:
                key:      "%secret%"
                lifetime: 604800
                path:     /
                domain:   ~

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin, roles: ROLE_ADMIN }