king_backend_homepage:
    path:     /admin
    defaults: { _controller: KingBackendBundle:Default:index }

king_backend_login:
    path:     /login
    defaults: { _controller: KingBackendBundle:Security:login }
king_backend_login_check:
    path: /login_check